defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{title}} (#{{number}})
        {{body}}
queue_rules:
  - name: default
    conditions:
      - check-success=test
      - check-success=blabla
      - check-success=Long CI nameuuuuuuuuu
      - check-success=CAPITAL BECAUSE WHY NOT
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5
    batch_size: 5
pull_request_rules:
  - name: automatic merge
    conditions:
      - label=autoqueue
    actions:
      queue:
        name: default
