queue_rules:
  - name: default
    merge_conditions:
      - check-success = proof-gate-6802
  - name: urgent
    conditions:
      - check-success = proof-gate-6802

pull_request_rules:
  - name: queue hotfixes
    conditions:
      - label = hotfix
    actions:
      queue:
        name: urgent
