extends: .github
queue_rules:
  - name: hotfix
    speculative_checks: 5
    merge_conditions:
      - and:
          - or:
              - check-neutral=test
              - check-failure=test
          - check-skipped!=test
      - and:
          - or:
              - '-label=docker'
              - check-success=docker-onpremise
          - check-success=semgrep
          - check-success=front (eslint)
          - check-success=front (test)
          - check-success=front (test:cf-page-worker)
          - check-success=front-component
          - check-success=front-e2e (1)
          - check-success=front-e2e (2)
          - check-success=front-e2e (3)
          - check-success=front-e2e (4)
          - check-success=front-e2e (5)
  - name: default
    speculative_checks: 5
    merge_conditions:
      - and:
          - or:
              - check-neutral=test
              - check-failure=test
          - check-skipped!=test
      - or:
          - or:
              - '-label=docker'
              - check-success=docker-onpremise
          - check-success=semgrep
          - check-success=front (eslint)
          - check-success=front (test)
          - check-success=front (test:cf-page-worker)
          - check-success=front-component
          - check-success=front-e2e (1)
          - check-success=front-e2e (2)
          - check-success=front-e2e (3)
          - check-success=front-e2e (4)
          - check-success=front-e2e (5)
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - and: &ref_0
          - or:
              - '-label=docker'
              - check-success=docker-onpremise
          - check-success=semgrep
          - check-success=front (eslint)
          - check-success=front (test)
          - check-success=front (test:cf-page-worker)
          - check-success=front-component
          - check-success=front-e2e (1)
          - check-success=front-e2e (2)
          - check-success=front-e2e (3)
          - check-success=front-e2e (4)
          - check-success=front-e2e (5)
      - schedule=Mon-Fri 09:00-17:00[Europe/Paris]
    batch_size: 7
    batch_max_wait_time: 5min
    queue_branch_merge_method: fast-forward
    disallow_checks_interruption_from_queues:
      - default
pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - base=main
      - author=@devs
      - check-success=semantic-pull-request
      - 'check-success=Rule: testing requirements (post_check)'
      - label=hotfix
      - title~=^(revert|fix)
      - schedule=Mon-Fri 09:00-17:00[Europe/Paris]
      - or: &ref_1
          - and:
              - author=@eng-mgr
              - '#approved-reviews-by>=1'
          - and:
              - author=@devs
              - or:
                  - approved-reviews-by=@eng-mgr
                  - and:
                      - title~=^(revert|fix)
                      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - '#review-requested=0'
      - label!=manual merge
    actions:
      queue:
        name: hotfix
  - name: automatic merge
    conditions:
      - base=main
      - check-success=semantic-pull-request
      - and: *ref_0
      - and: *ref_1
      - 'check-success=Rule: testing requirements (post_check)'
      - 'check-success=Rule: changelog requirements (post_check)'
      - '#approved-reviews-by>=2'
      - '#changes-requested-reviews-by=0'
      - '#review-requested=0'
      - '#review-threads-unresolved=0'
      - label!=manual merge
    actions:
      queue: 
  - name: automatic merge from dependabot
    conditions:
      - and: *ref_0
      - check-success=semantic-pull-request
      - author=dependabot[bot]
      - label!=manual merge
      - '#commits=1'
    actions:
      queue:
        name: lowprio
        method: merge
        commit_message_template: 
  - name: request review
    conditions:
      - '-author=dependabot[bot]'
      - '-author=mergify-ci-bot'
      - '-merged'
      - '-closed'
      - and: *ref_0
      - 'check-success=Rule: testing requirements (post_check)'
      - '#approved-reviews-by=0'
      - '#changes-requested-reviews-by=0'
      - review-requested!=@devs
    actions:
      request_reviews:
        teams:
          - devs
  - name: testing requirements
    conditions:
      - or:
          - label=skip tests
          - '-title~=^(feat|fix)'
          - files~=src/tests
          - files~=^cypress/component
          - files~=^cypress/e2e
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Testing requirements are present.
          {% else %}
          Testing requirements are missing.
          {% endif %}
