defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{title}} (#{{number}})

        {{body}}

queue_rules:
  - name: hotfix
    conditions:
        - check-success=test
    speculative_checks: 5

  - name: default
    allow_inplace_checks: true
    conditions:
      - check-success=test
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - check-success=test
      - schedule=Mon-Fri 09:30-17:00[Europe/Paris]
    speculative_checks: 3
    batch_size: 5

pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - label=hotfix
    actions:
      queue:
        name: hotfix
        
  - name: copy pull request when CI passes
    conditions:
      - base=main
      - label=armageddon
    actions:
      label:
        add:
          - hotfix
          - autoqueue
          - truc
          - blabla
        
  - name: automatic merge
    conditions:
      - label=autoqueue
    actions:
      queue:
        name: default