<<<<<<< HEAD
defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{title}} (#{{number}})

        {{body}}

queue_rules:
  - name: hotfix
    conditions:
        - check-success=test
    speculative_checks: 5

  - name: default
    allow_inplace_checks: true
    conditions:
      - check-success=test
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - check-success=test
      - schedule=Mon-Fri 09:30-17:00[Europe/Paris]
    speculative_checks: 3
    batch_size: 5

pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - base=main
      - label=hotfix
    actions:
      queue:
        name: hotfix
        
  - name: automatic merge
    conditions:
      - base=main
      - label=autoqueue
    actions:
      queue:
        name: default
=======
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
>>>>>>> 05b2cb3 (ci(Mergify): configuration update)
