defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{title}} (#{{number}})

        {{body}}

queue_rules:
  - name: hotfix
    allow_inplace_checks: true
    conditions:
      - and: &CheckRuns
          - check-success=requirements
          - check-success=docker
          - check-success=pep8
          - check-success=test
          - check-success=react
          - check-success=datadog
          - or:
              - check-success=dbdiff
              - label=Skip dbdiff
    speculative_checks: 5

  - name: default
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:30-17:00[Europe/Paris]
    speculative_checks: 3
    batch_size: 5

pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - base=main
      - author=@devs
      - check-success=semantic-pull-request
      - label=hotfix
      - title~=^(revert|fix)
      - or:
          # We authorize hotfix to go through if they fix a sentry
          - body~=(?m)^Fixes MERGIFY-(DASHBOARD|REACT)-
          - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: hotfix

  - name: automatic merge
    conditions:
      - base=main
      - check-success=semantic-pull-request
      - and: *CheckRuns
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:

  - name: automatic merge for python version bump
    conditions:
      - and: *CheckRuns
      - check-success=semantic-pull-request
      - author=mergify-ci-bot
      - label!=work-in-progress
      - label!=manual merge
      - "title~=^chore: bump python version"
      - head=python-version-upgrade
      - "#commits=1"
    actions:
      queue:
        name: lowprio
        method: rebase
        commit_message_template: null

  - name: automatic merge from dependabot
    conditions:
      - and: *CheckRuns
      - check-success=semantic-pull-request
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: lowprio
        method: rebase
        commit_message_template: null

  - name: dependabot conflict fixer
    conditions:
      - author=dependabot[bot]
      - conflict
    actions:
      comment:
        bot_account: mergify-ci-bot
        message: "@dependabot recreate"

  - name: dismiss reviews except for core devs
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: False
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - label!=work-in-progress
      - -merged
      - -closed
      - and: *CheckRuns
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
    actions:
      request_reviews:
        teams:
          - devs
  - name: warn on no Sentry
    conditions:
      - -body~=(?m)^Fixes MERGIFY-(DASHBOARD|REACT)-
      - label=hotfix
    actions:
      comment:
        message: Your pull request is a hotfix but does not fix a Sentry issue. 🤔
  - name: warn on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: label on unresolved
    conditions:
      - "#review-threads-unresolved>0"
    actions:
      label:
        add:
          - Review Threads Unresolved

  - name: unlabel on resolved
    conditions:
      - "#review-threads-unresolved=0"
    actions:
      label:
        remove:
          - Review Threads Unresolved

  - name: warn on CI failure for hotfix
    conditions:
      - label=hotfix
      - "#check-failure>0"
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺
