defaults:
  actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{title}} (#{{number}})

        {{body}}

queue_rules:
  - name: hotfix
    conditions:
        - check-success=test
        - check-success=blabla
        - check-success=Long CI nameuuuuuuuuu
        - check-success=CAPITAL BECAUSE WHY NOT
        - schedule=Sat-Sun 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: default
    allow_inplace_checks: true
    conditions:
        - check-success=test
        - check-success=blabla
        - check-success=Long CI nameuuuuuuuuu
        - check-success=CAPITAL BECAUSE WHY NOT
        - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
    speculative_checks: 5

  - name: lowprio
    allow_inplace_checks: true
    conditions:
      - check-success=test
      - schedule=Mon-Fri 09:30-17:00[Europe/Paris]
    speculative_checks: 3
    batch_size: 5

pull_request_rules:
  - name: automatic merge for hotfix
    conditions:
      - label=hotfix
    actions:
      queue:
        name: hotfix
        
  - name: Update PR
    conditions:
        - label=update
    actions:
        update:

  - name: Armageddon
    conditions:
      - label=armageddon
    actions:
      label:
        add:
          - hotfix
          - autoqueue
          - soap
          - blabla
      assign:
        add_users:
          - Machin
          - Truc
      backport:
        branches:
          - hotfix
      comment:
          message: |
            blabla
      comment:
          message: |
            blabla
      edit:
        draft: True
      comment:
          message: |
            blabla
      comment:
          message: |
            blabla
      review:
        type: APPROVE
        message: Automatically approving dependabot
      review:
        type: REQUEST_CHANGES
        message: Request changes
      edit:
        draft: False

        
  - name: automatic merge
    conditions:
      - label=autoqueue
    actions:
      queue:
        name: default
