queue_rules:
    - name: hotfix
      merge_conditions:
          - check-success=test
      speculative_checks: 5

pull_request_rules:
    - name: trigger ci
      conditions:
          - author=sileht
      actions:
          backport:
              ignore_conflicts: true
              label_conflicts: conflicts